formula: condition
tool_setting: 
  type: rsem
quantification_output_extension: .genes.results
contrast: 
  condition: 
    - 'KO_21,WT_21'
    - 'KO_35,WT_35'
pvalue_cutoff: 0.01
log2fc_cutoff: 0.5
