cluster: "submit.py"

cluster-status: "jobstatus.py"
cluster-config: "profiles/groups_config.yaml"
jobscript: "jobscript.sh"
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
rerun-incomplete: true
restart-times: 3
keep-going: true
notemp: false
immediate-submit: false
latency-wait: 60
verbose: true
reason: true
printshellcmds: true
jobs: 6